// Original quote artwork, ordered intentionally. Download always uses the original.
export const quotes = [
  { id: 'awad', src: '/images/quotes/awad.jpg', width: 714, height: 1280, alt: 'عوضه ليس مجرد بديل؛ هو دهشة تخطف الروح، وتنسيك مرارة الصبر. توقيع سامح محمد عبد الظاهر.' },
  { id: 'heart', src: '/images/quotes/heart.jpg', width: 714, height: 1280, alt: 'لم نكبر حين كثر الرغيف، بل حين صغر القلب. توقيع سامح محمد عبد الظاهر.' },
  { id: 'world', src: '/images/quotes/world.jpg', width: 714, height: 1280, alt: 'لا تجعل جدارًا واحدًا يختصر لك العالم؛ أنت لم تر الحياة بعد، أنت فقط رأيت الجزء الذي أوجعك منها. توقيع سامح محمد عبد الظاهر.' },
  { id: 'courage', src: '/images/quotes/courage.jpg', width: 714, height: 1280, alt: 'البطولة هي أن تملك شجاعة الغسيل كلما تلطخت بوحل الدنيا. توقيع سامح محمد عبد الظاهر.' },
  { id: 'giving', src: '/images/quotes/giving.jpg', width: 714, height: 1280, trim: true, alt: 'أحيانًا، تكون قمة العطاء الإلهي.. في الحرمان. توقيع سامح محمد عبد الظاهر.' },
];

export function quoteGallery(escape) {
  return `<section class="section container" id="my-words" aria-labelledby="my-words-title"><div class="section-heading"><div><p class="eyebrow">من كلماتي</p><h2 id="my-words-title">من كلماتي</h2></div><span class="muted">كلمات بخطّها وتوقيعها الأصلي</span></div><div class="quote-gallery">${quotes.map((quote, index) => `<article class="quote-card ${index === 0 ? 'quote-featured' : ''}" data-quote-id="${quote.id}"><a class="quote-open" href="${quote.src}" aria-label="عرض الاقتباس بحجم أكبر: ${escape(quote.alt)}"><span class="quote-frame ${quote.trim ? 'quote-frame-trimmed' : ''}"><img src="${quote.src}" alt="${escape(quote.alt)}" width="${quote.width}" height="${quote.height}" loading="lazy" decoding="async"></span></a><div class="quote-actions"><a href="${quote.src}" download="sameh-${quote.id}.jpg">تحميل الأصل</a><button type="button" class="quote-share" data-url="${quote.src}" data-title="${escape(quote.alt)}">مشاركة</button><a href="${quote.src}" target="_blank" rel="noopener">فتح الصورة</a></div><p class="quote-status" role="status" aria-live="polite"></p><input class="quote-share-link" type="text" readonly hidden aria-label="رابط صورة الاقتباس للنسخ اليدوي"></article>`).join('')}</div></section><dialog id="quote-dialog" class="quote-dialog" aria-labelledby="quote-dialog-title"><form method="dialog"><button class="close-dialog" aria-label="إغلاق صورة الاقتباس">×</button></form><h2 id="quote-dialog-title">من كلماتي</h2><div id="quote-view"></div><a id="quote-download" class="text-link" download>تحميل الصورة الأصلية</a></dialog>`;
}
