import { author, books, policies, writings } from './content.js';
import { siteUrl, structuredData } from './seo.js';
import { siteAssets } from './site-config.js';
export const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const price = book => `${book.price} جنيه مصري`;
const paragraphs = text => text.split('\n\n').map(paragraph => `<p>${escape(paragraph)}</p>`).join('');
function cover(book, small = false) {
  return book.cover ? `<img class="cover-image" src="${escape(book.cover)}" alt="${escape(book.coverAlt || `غلاف ${book.title}`)}" width="${book.coverWidth}" height="${book.coverHeight}" decoding="async" ${small ? 'loading="lazy"' : 'loading="eager" fetchpriority="high"'}>` : `<div class="cover-placeholder ${small ? 'small' : ''}" role="img" aria-label="مساحة مؤقتة لغلاف الكتاب الأصلي"><span class="cover-corner"></span><span class="cover-mark">س</span><span class="cover-label">مساحة الغلاف الأصلي</span><span class="cover-note">ستُضاف صورة الغلاف قريبًا</span></div>`;
}
const brand = () => `<span class="brand-name">${escape(author.name)}</span><span>${escape(author.role)}</span>`;
const buy = book => `<button class="button buy-button" data-book-id="${escape(book.id)}">اشترِ الكتاب <span aria-hidden="true">↗</span></button>`;
function home() {
  const book = books[0];
  return `<section class="hero container" id="home" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow"><span></span> الموقع الرسمي للكاتب</p><p class="author-intro">${escape(author.name)}<span class="author-role">${escape(author.role)}</span></p><h1 id="hero-title">${escape(book.title)}</h1><p class="subtitle">${escape(book.subtitle)}</p><div class="short-rule"></div><p class="hero-description">خواطر وتأملات في النفس والحياة، وما تتركه العلاقات فينا من أثر. صفحات عن تجارب إنسانية قد نجد فيها شيئًا من أنفسنا.</p><div class="purchase-line"><div><span class="price">${book.price}</span><span class="currency">جنيه مصري</span></div>${buy(book)}</div><a class="text-link" href="#about-book">تعرّف على الكتاب <span aria-hidden="true">↓</span></a></div><div class="hero-art">${cover(book)}<span class="art-caption">الكتاب الأول <span aria-hidden="true">—</span> ${escape(book.subtitle)}</span></div></section>
  <section class="book-about section" id="about-book"><div class="container about-grid"><div><p class="eyebrow">01 / عن الكتاب</p><h2>بين ما نشعر به،<br>وما نستطيع قوله.</h2></div><div><div class="large-copy">${paragraphs(book.description)}</div><p class="muted">كتابة أدبية عن التجربة الإنسانية؛ ليست كتابًا علاجيًا أو طبيًا.</p><div class="tags"><span>النفس الإنسانية</span><span>العلاقات</span><span>مواقف من الحياة</span></div></div></div></section>
  <section class="section container" id="excerpts"><div class="section-heading"><div><p class="eyebrow">02 / الكتابات والمقتطفات</p><h2>الكتابات والمقتطفات</h2></div><span class="muted">مساحة للقراءة والتأمل</span></div>${writings.length ? `<div class="excerpt-grid">${writings.map(w => `<article><h3>${escape(w.title)}</h3><p>${escape(w.text)}</p></article>`).join('')}</div>` : ''}${book.excerpts.length ? `<div class="excerpt-grid">${book.excerpts.map(t => `<blockquote>${escape(t)}</blockquote>`).join('')}</div>` : `<div class="excerpt-empty"><span class="quote-mark" aria-hidden="true">”</span><p>هنا، مساحة للكتابات ومقتطفات من الكتاب.</p><span class="muted">ستُضاف كتابات ومقتطفات أصلية يعتمدها الكاتب قريبًا.</span></div>`}</section>
  <section class="author-section section" id="author"><div class="container author-grid"><figure class="author-portrait"><picture><source srcset="${escape(author.portrait.src)}" type="image/webp"><img src="${escape(author.portrait.original)}" alt="${escape(author.portrait.alt)}" width="${author.portrait.width}" height="${author.portrait.height}" loading="lazy" decoding="async"></picture></figure><div><p class="eyebrow">03 / عن الكاتب</p><h2>${escape(author.name)}</h2><p class="author-role">${escape(author.role)}</p><div class="bio">${paragraphs(author.bio)}</div></div></div></section>
  <section class="section container" id="books"><div class="section-heading"><div><p class="eyebrow">04 / الكتب</p><h2>الكتب</h2></div><span class="muted">تبدأ المكتبة بكتاب</span></div><div class="books-grid">${books.map(b => `<article class="book-card">${cover(b, true)}<div><h3>${escape(b.title)}</h3><p>${escape(b.subtitle)}</p><div class="book-card-description">${paragraphs(b.description)}</div><p class="book-price">${price(b)}</p>${buy(b)}</div></article>`).join('')}</div></section>
  <section class="contact section" id="contact"><div class="container"><p class="eyebrow">05 / تواصل</p><h2>تواصل</h2><p>للكلمة مساحة، وللتواصل أيضًا.</p><p>${author.email ? `<a href="mailto:${escape(author.email)}">${escape(author.email)}</a>` : 'ستُضاف وسيلة التواصل الرسمية بعد اعتمادها من الكاتب.'}</p></div></section>
  <dialog id="order-dialog" aria-labelledby="order-title"><form method="dialog"><button class="close-dialog" aria-label="إغلاق نافذة الطلب">×</button></form><p class="eyebrow">طلب الكتاب</p><h2 id="order-title">${escape(book.title)}</h2><p id="order-subtitle">${escape(book.subtitle)}</p><div class="order-summary"><span>النسخة الإلكترونية</span><strong id="order-price">${price(book)}</strong></div><p class="notice">الشراء والدفع غير مفعّلين حاليًا. هذه واجهة تمهيدية للطلب؛ لا تُجمع بيانات شخصية ولا يُخصم أي مبلغ.</p><p class="muted">بعد ربط الدفع، سيُؤكَّد على الخادم قبل إتاحة نسخة خاصة للتحميل.</p><button class="button" id="checkout-button" type="button">تحقّق من إتاحة الشراء</button><p id="order-status" role="status" aria-live="polite"></p><a class="text-link" href="/purchase-policy">سياسة الشراء والاسترجاع</a></dialog>`;
}
export function render(path = '/') {
  const policy = policies[path];
  const missing = path !== '/' && !policy;
  const title = policy ? `${policy.title} | ${author.name}` : missing ? `الصفحة غير موجودة | ${author.name}` : `${author.name} | ${author.role} — الموقع الرسمي`;
  const description = policy ? `${policy.title} — مسودة تحتاج مراجعة قبل الإطلاق.` : `${books[0].title}، ${books[0].subtitle}. الموقع الرسمي للكاتب ${author.name}، ${author.role}. ${books[0].description}`;
  const assetMeta = `${siteAssets.favicon ? `<link rel="icon" href="${escape(siteAssets.favicon)}">` : ''}${siteAssets.socialImage ? `<meta property="og:image" content="${escape(new URL(siteAssets.socialImage, siteUrl()).href)}"><meta name="twitter:image" content="${escape(new URL(siteAssets.socialImage, siteUrl()).href)}">` : ''}`;
  const body = policy ? `<section class="container legal section"><p class="eyebrow">المعلومات والسياسات</p><h1>${escape(policy.title)}</h1><p class="notice">مسودة هيكلية مؤقتة تحتاج مراجعة واعتمادًا قبل الإطلاق وتفعيل الشراء. هذه الصفحة لا تنشئ التزامات قانونية أو وعودًا بالاسترجاع أو التسليم.</p>${policy.topics.map(t => `<h2>${escape(t)}</h2><p class="muted">نص مؤقت: يُستكمل بعد تحديد إجراءات التشغيل ومراجعته قانونيًا قبل النشر.</p>`).join('')}<a class="text-link" href="/">العودة إلى الرئيسية ←</a></section>` : missing ? `<section class="container legal section"><p class="eyebrow">404</p><h1>هذه الصفحة ليست هنا.</h1><p>ربما تغيّر الطريق؛ يمكنك العودة إلى بداية الحكاية.</p><a class="button" href="/">العودة إلى الرئيسية</a></section>` : home();
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#f6f2e9">${assetMeta}${policy || missing ? '<meta name="robots" content="noindex, follow">' : ''}<link rel="canonical" href="${escape(siteUrl() + (missing ? '/404' : path))}"><meta property="og:type" content="website"><meta property="og:locale" content="ar_EG"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${escape(siteUrl() + path)}"><meta name="twitter:card" content="${siteAssets.socialImage ? 'summary_large_image' : 'summary'}"><meta name="twitter:title" content="${escape(title)}"><meta name="twitter:description" content="${escape(description)}"><link rel="stylesheet" href="/styles.css">${path === '/' ? `<script type="application/ld+json">${JSON.stringify(structuredData()).replace(/</g, '\\u003c')}</script>` : ''}<script type="module" src="/app.js"></script></head><body><a class="skip-link" href="#main">انتقل إلى المحتوى</a><header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="${escape(author.name)} — الرئيسية">${brand()}</a><nav aria-label="التنقل الرئيسي"><a href="/#home">الرئيسية</a><a href="/#about-book">عن الكتاب</a><a href="/#author">عن الكاتب</a><a href="/#books">الكتب</a><a href="/#excerpts">الكتابات والمقتطفات</a><a href="/#contact">تواصل</a></nav><a class="header-book" href="/#books">الكتب <span aria-hidden="true">↗</span></a></div></header><main id="main">${body}</main><footer><div class="container footer-top"><div><a class="brand" href="/">${brand()}</a><p>الموقع الرسمي للكاتب</p></div><nav aria-label="السياسات">${Object.entries(policies).map(([p, v]) => `<a href="${p}">${v.title}</a>`).join('')}</nav></div><div class="container footer-bottom"><span>© ${new Date().getUTCFullYear()} ${escape(author.name)}</span><span>كلمات من التجربة، ومساحة للإنسان.</span></div></footer></body></html>`;
}
